# Generated by Django 2.2.6 on 2019-10-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Foto'),
        ),
    ]
