# Generated by Django 2.2.6 on 2019-10-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20191003_0431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='author',
        ),
    ]
