# Generated by Django 2.2.6 on 2019-10-03 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20191003_0929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='id_photo',
        ),
    ]
