# Generated by Django 2.2.6 on 2019-10-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_auto_20191003_1416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photos',
            options={'ordering': ['-created', '-quant_like'], 'verbose_name': 'Foto', 'verbose_name_plural': 'Fotos'},
        ),
        migrations.AlterField(
            model_name='like',
            name='author',
            field=models.IntegerField(verbose_name='id_user'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id_photo',
            field=models.IntegerField(verbose_name='id_foto'),
        ),
    ]
